server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?useSSL=false&serverTimezone=Asia/Tokyo
    username: root
    password: Heute666
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.todo.model
  configuration:
    map-underscore-to-camel-case: true
